export const POKEMON_TYPES = [
  'normal',
  'fire',
  'water',
  'electric',
  'grass',
  'ice',
  'fighting',
  'poison',
  'ground',
  'flying',
  'psychic',
  'bug',
  'rock',
  'ghost',
  'dragon',
  'dark',
  'steel',
  'fairy',
] as const;

export const GENERATION_OPTIONS = [
  { label: 'Gen 1', value: '1' },
  { label: 'Gen 2', value: '2' },
  { label: 'Gen 3', value: '3' },
  { label: 'Gen 4', value: '4' },
  { label: 'Gen 5', value: '5' },
  { label: 'Gen 6', value: '6' },
  { label: 'Gen 7', value: '7' },
  { label: 'Gen 8', value: '8' },
  { label: 'Gen 9', value: '9' },
] as const;